const tabs=[...document.querySelectorAll('.core-tab')];
const panels=[...document.querySelectorAll('.core-panel')];
let demoTimer;
function countUp(root=document){root.querySelectorAll('[data-count]').forEach(el=>{if(el.dataset.done)return;el.dataset.done='1';const end=Number(el.dataset.count),start=performance.now(),duration=1300;function tick(now){const p=Math.min((now-start)/duration,1);el.textContent=Math.round(end*(1-Math.pow(1-p,3))).toLocaleString();if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)})}
function typeXO(){const el=document.getElementById('xoTyping');if(!el)return;const text=el.dataset.text;el.textContent='';let i=0;clearInterval(window.xoType);window.xoType=setInterval(()=>{el.textContent=text.slice(0,++i);if(i>=text.length)clearInterval(window.xoType)},34)}
function runMeasurement(){const visual=document.querySelector('.measure-visual'),panel=document.querySelector('[data-view="measurements"]'),button=document.querySelector('.chat-scan'),status=document.querySelector('.scan-status'),steps=[...document.querySelectorAll('.measure-steps b')];if(!visual)return;visual.classList.remove('scanning');panel.querySelectorAll('[data-count]').forEach(el=>{delete el.dataset.done;el.textContent='0'});steps.forEach(s=>s.classList.remove('done'));button?.classList.add('running');if(status)status.innerHTML='Scanning report <b>→</b>';void visual.offsetWidth;visual.classList.add('scanning');setTimeout(()=>{steps[0]?.classList.add('done');countUp(panel)},350);setTimeout(()=>steps[1]?.classList.add('done'),2250);setTimeout(()=>{steps[2]?.classList.add('done');if(status)status.innerHTML='Applied to estimate <b>✓</b>';button?.classList.remove('running')},4300)}
function selectPanel(name){tabs.forEach(t=>{const on=t.dataset.panel===name;t.classList.toggle('active',on);t.setAttribute('aria-selected',on)});panels.forEach(p=>p.classList.toggle('active',p.dataset.view===name));const active=document.querySelector(`.core-panel[data-view="${name}"]`);countUp(active);if(name==='measurements'){typeXO();setTimeout(runMeasurement,350)}}
tabs.forEach(tab=>tab.addEventListener('click',()=>{clearInterval(demoTimer);selectPanel(tab.dataset.panel)}));
function runDemo(){let i=0;selectPanel(tabs[0].dataset.panel);clearInterval(demoTimer);demoTimer=setInterval(()=>{i=(i+1)%tabs.length;selectPanel(tabs[i].dataset.panel);if(i===tabs.length-1)setTimeout(()=>clearInterval(demoTimer),3200)},3200)}
document.getElementById('playDemo')?.addEventListener('click',runDemo);document.querySelector('.demo-trigger')?.addEventListener('click',()=>selectPanel('estimates'));
document.querySelector('.chat-scan')?.addEventListener('click',runMeasurement);
const coreObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){typeXO();setTimeout(runMeasurement,550);coreObserver.disconnect()}}),{threshold:.22});const core=document.querySelector('.core-live');if(core)coreObserver.observe(core);
const globalCounter=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)countUp(e.target)}),{threshold:.4});document.querySelectorAll('.service,.journey').forEach(e=>globalCounter.observe(e));
