const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function animateEstimate(){const panel=document.querySelector('[data-view="estimates"]'),button=document.querySelector('.send-estimate'),total=document.getElementById('estimateTotal');if(!panel||!button)return;panel.classList.remove('action-running');total.textContent='$0';button.textContent='Building estimate…';void panel.offsetWidth;panel.classList.add('action-running');await sleep(1700);let start=performance.now(),end=22197;function frame(now){const p=Math.min((now-start)/950,1);total.textContent='$'+Math.round(end*p).toLocaleString();if(p<1)requestAnimationFrame(frame)}requestAnimationFrame(frame);await sleep(1100);button.textContent='Send for approval →';button.classList.remove('sent')}
document.querySelector('.send-estimate')?.addEventListener('click',async e=>{if(e.currentTarget.textContent.includes('Build'))return animateEstimate();e.currentTarget.textContent='Sent for approval ✓';e.currentTarget.classList.add('sent')});
document.querySelector('.sign-demo')?.addEventListener('click',async e=>{const panel=e.currentTarget.closest('.core-panel'),pending=panel.querySelector('.pending-doc'),time=panel.querySelector('.sign-time');panel.classList.remove('signing');void panel.offsetWidth;panel.classList.add('signing');e.currentTarget.textContent='Signature request sent…';await sleep(2300);time.textContent='Signed just now · Identity verified';pending.classList.add('complete');pending.querySelector('i').textContent='✓';pending.querySelector('em').textContent='Complete';e.currentTarget.textContent='Signed ✓'});
document.querySelector('.payment-demo')?.addEventListener('click',async e=>{const panel=e.currentTarget.closest('.core-panel');panel.classList.remove('payment-live');void panel.offsetWidth;panel.classList.add('payment-live');e.currentTarget.textContent='Processing payment…';await sleep(650);document.getElementById('paidTotal').textContent='$72,670';document.getElementById('outstandingTotal').textContent='$10,510';e.currentTarget.textContent='Payment received ✓'});
document.querySelector('.calendar-book')?.addEventListener('click',e=>{document.querySelector('.demo-event').classList.add('booked');e.currentTarget.textContent='Demo added to Google Calendar ✓'});
document.querySelector('.advance-project')?.addEventListener('click',e=>{const card=e.currentTarget.closest('.project-card'),bar=card.querySelector('.progress i'),num=card.querySelector('.project-percent');bar.style.width='84%';num.textContent='84';e.currentTarget.textContent='Progress updated ✓'});
document.querySelector('.automation-run')?.addEventListener('click',async e=>{const panel=e.currentTarget.closest('.core-panel');panel.classList.remove('flow-live');void panel.offsetWidth;panel.classList.add('flow-live');e.currentTarget.textContent='AI agent is following up…';await sleep(2500);e.currentTarget.textContent='Lead replied · Team notified ✓'});
document.querySelectorAll('.core-tab').forEach(tab=>tab.addEventListener('click',()=>{const n=tab.dataset.panel;if(n==='estimates')setTimeout(animateEstimate,350)}));
const refreshMeetingSummary=()=>{const date=document.querySelector('.date-choice.active'),time=document.querySelector('.time-choice.active'),summary=document.querySelector('.meeting-summary span:first-child b');if(!date||!time||!summary)return;const day=date.querySelector('small')?.textContent||'',number=date.querySelector('b')?.textContent||'';summary.textContent=`${day}, Sep ${number} · ${time.textContent}`};
document.querySelectorAll('.date-choice').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.date-choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');refreshMeetingSummary()}));document.querySelectorAll('.time-choice').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.time-choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');refreshMeetingSummary()}));
document.getElementById('bookDemoButton')?.addEventListener('click',()=>{document.querySelector('.booking-success').classList.add('show')});
